from pathlib import Path
from PIL import Image, ImageSequence


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "actual_project" / "sprite_roms.v"

SPRITES = [
    ("madeline_idle_rom", ROOT / "Images" / "madeline-idle.gif", 7),
    ("run_slow_rom", ROOT / "Images" / "runSlow.gif", 12),
    ("strawberry_rom", ROOT / "Images" / "strawberry.gif", 7),
    ("spike_sprite_rom", ROOT / "Images" / "Spike-Sprite.png", 1),
]


def rgba_frames(path, frame_count):
    image = Image.open(path)
    frames = list(ImageSequence.Iterator(image)) if getattr(image, "is_animated", False) else [image]
    frames = frames[:frame_count]
    while len(frames) < frame_count:
        frames.append(frames[-1])

    out = []
    for frame in frames:
        rgba = frame.convert("RGBA").resize((16, 16), Image.Resampling.LANCZOS)
        out.append(rgba)
    return out


def pixel_word(pixel):
    r, g, b, a = pixel
    if a < 64:
        return "13'b0_0000_0000_0000"
    return f"13'b1_{r >> 4:04b}_{g >> 4:04b}_{b >> 4:04b}"


def write_module(f, module_name, path, frame_count):
    frames = rgba_frames(path, frame_count)
    frame_bits = max(1, (frame_count - 1).bit_length())
    depth = frame_count * 16 * 16

    f.write(f"module {module_name}(\n")
    f.write(f"    input wire [{frame_bits - 1}:0] frame,\n")
    f.write("    input wire [3:0] row,\n")
    f.write("    input wire [3:0] col,\n")
    f.write("    output wire [11:0] color_data,\n")
    f.write("    output wire opaque\n")
    f.write(");\n\n")
    f.write(f"    reg [12:0] rom [0:{depth - 1}];\n")
    f.write("    wire [12:0] sprite_word;\n")
    if frame_count == 1:
        f.write("    wire [7:0] addr = {row, col};\n\n")
    else:
        f.write(f"    wire [{frame_bits - 1}:0] safe_frame = (frame < {frame_bits}'d{frame_count}) ? frame : {frame_bits}'d0;\n")
        f.write(f"    wire [{frame_bits + 7}:0] addr = {{safe_frame, row, col}};\n\n")

    f.write("    initial begin\n")
    for frame_index, frame in enumerate(frames):
        for row in range(16):
            for col in range(16):
                addr = frame_index * 256 + row * 16 + col
                f.write(f"        rom[{addr}] = {pixel_word(frame.getpixel((col, row)))};\n")
    f.write("    end\n\n")
    f.write("    assign sprite_word = rom[addr];\n")
    f.write("    assign opaque = sprite_word[12];\n")
    f.write("    assign color_data = sprite_word[11:0];\n")
    f.write("endmodule\n\n")


def main():
    with OUT.open("w", newline="\n") as f:
        f.write("// Auto-generated by scripts/generate_sprite_roms.py.\n")
        f.write("// 16x16 sprites, 12-bit RGB plus one opaque bit.\n\n")
        for sprite in SPRITES:
            write_module(f, *sprite)


if __name__ == "__main__":
    main()
